// Annotations for the starter library, keyed by node id (see seed.js for ids).
// when: the situation that opens the option · oc: where it lands (common / rare) · f: how common a defense is
// gi: gi | nogi | both · belt: lowest belt it is usually taught at · kids:false = not allowed in kids divisions
// bait: a trap (what you offer and what you want them to do) · legal: rules note · energy 1-3 · pts IBJJF points
window.BJJ_META = {
  /* ───── Standing ───── */
  'st.1': { gi: 'gi', when: 'Neutral, both standing', energy: 1 },
  'st.1.1': { f: 'common' }, 'st.1.2': { f: 'common' }, 'st.1.3': { f: 'common' },
  'st.1.1.2': { when: 'They pull the arm back after the break', oc: [{ to: 'bk_t', f: 'common' }, { to: 'tt_t', f: 'common' }] },
  'st.1.3.1': { pts: 0, oc: [{ to: 'tt_t', f: 'common' }, { to: 'sc_t', f: 'rare' }], legal: 'No points until a top position is settled' },
  'st.2': { when: 'They reach or extend an arm', energy: 1 },
  'st.2.1': { f: 'common' }, 'st.2.2': { f: 'rare' },
  'st.3': { gi: 'gi', when: 'They push or lean into you', energy: 3, oc: [{ to: 'sc_t', f: 'common' }, { to: 'kob_t', f: 'rare' }, { to: 'tt_t', f: 'rare' }], legal: 'Kids: no throws that land on the head/neck' },
  'st.3.1': { f: 'common' }, 'st.3.2': { f: 'rare' },
  'st.4': { when: 'They stand square or stall', energy: 3, oc: [{ to: 'sc_t', f: 'common' }, { to: 'hg_t', f: 'common' }, { to: 'og_t', f: 'rare' }, { to: 'tt_t', f: 'rare' }] },
  'st.4.1': { f: 'common' }, 'st.4.2': { f: 'common' }, 'st.4.3': { f: 'rare' },
  'st.5': { when: 'They stand square or stall', energy: 3, oc: [{ to: 'sc_t', f: 'common' }, { to: 'hg_t', f: 'common' }, { to: 'cg_t', f: 'rare' }, { to: 'og_t', f: 'rare' }] },
  'st.5.1': { f: 'common' }, 'st.5.2': { f: 'common' },
  'st.6': { when: 'They push or lean into you', energy: 2, oc: [{ to: 'sc_t', f: 'common' }, { to: 'mt_t', f: 'rare' }] },
  'st.6.1': { f: 'common' },
  'st.7': { when: 'Neutral, both standing', energy: 1, pts: 0, oc: [{ to: 'cg_b', f: 'common' }, { to: 'og_t', f: 'rare' }], legal: 'IBJJF: pulling guard scores nothing; a takedown right after gives them 2' },
  'st.7.1': { f: 'common' },
  'st.8': { when: 'They reach or extend an arm', belt: 'blue', energy: 3, kids: false, legal: 'IBJJF: jumping to guard/flying attacks are not allowed for white belts or kids', oc: [{ to: 'cg_b', f: 'common' }] },
  'st.8.1': { f: 'common' }, 'st.8.2': { f: 'rare' },
  'st.9': { when: 'They bend forward, head heavy', energy: 2, oc: [{ to: 'sc_t', f: 'common' }, { to: 'og_t', f: 'common' }] },
  'st.9.1': { f: 'common' },
  'st.10': { gi: 'both', belt: 'blue', when: 'They push or lean into you', energy: 3, oc: [{ to: 'sc_t', f: 'common' }, { to: 'mt_t', f: 'rare' }] },
  'st.10.1': { f: 'common' },
  'st.11': { when: 'They stand square or stall', energy: 1, oc: [{ to: 'sc_t', f: 'common' }, { to: 'og_t', f: 'common' }] },
  'st.12': { when: 'They push or lean into you', belt: 'blue', energy: 2, oc: [{ to: 'mt_t', f: 'common' }, { to: 'sc_t', f: 'rare' }] },
  'st.13': { gi: 'both', when: 'Clinch or underhook battle', energy: 3, oc: [{ to: 'sc_t', f: 'common' }, { to: 'hg_t', f: 'common' }, { to: 'bk_t', f: 'rare' }] },
  'st.13.1': { f: 'common' },
  'st.14': { gi: 'gi', when: 'Neutral, both standing', energy: 1 },
  'st.14.1': { f: 'common' },
  'st.14.1.1': { oc: [{ to: 'bk_t', f: 'common' }, { to: 'tt_t', f: 'common' }] },
  'st.15': { gi: 'nogi', when: 'Neutral, both standing', energy: 1 },
  'st.16': { gi: 'gi', when: 'Neutral, both standing', pts: 0 },
  'st.17': { when: 'Neutral, both standing', pts: 0 },
  'st.18': { when: 'They bend forward, head heavy', energy: 2, oc: [{ to: 'cg_b', f: 'common' }] },
  'st.18.1': { f: 'common' },
  'st.19': { when: 'They pull guard', energy: 2, pts: 0, oc: [{ to: 'og_t', f: 'common' }, { to: 'sc_t', f: 'rare' }] },

  /* ───── Closed guard ───── */
  'cg_b.1': { when: 'They post a hand on you or the mat', bait: 'The bump is bait: the hand they post is what you want for the kimura, and the pull-out for the guillotine', oc: [{ to: 'mt_t', f: 'common' }, { to: 'sc_t', f: 'rare' }] },
  'cg_b.1.1': { f: 'common' }, 'cg_b.1.2': { f: 'common' },
  'cg_b.2': { gi: 'both', when: 'They posture up, hands on your hips', oc: [{ to: 'mt_t', f: 'common' }, { to: 'hg_t', f: 'rare' }] },
  'cg_b.2.1': { f: 'common' }, 'cg_b.2.2': { f: 'rare' },
  'cg_b.3': { when: 'An arm crosses the centre line', energy: 2 },
  'cg_b.3.1': { f: 'common' }, 'cg_b.3.2': { f: 'common', bait: 'Some stand to bait the triangle attempt and pass as you swing the leg' },
  'cg_b.4': { when: 'An arm crosses the centre line', energy: 2 },
  'cg_b.4.1': { f: 'common' }, 'cg_b.4.2': { f: 'rare' },
  'cg_b.5': { when: 'They post a hand on you or the mat', energy: 2 },
  'cg_b.5.1': { f: 'common' },
  'cg_b.6': { gi: 'gi', when: 'Posture broken, head down' },
  'cg_b.6.1': { f: 'common' },
  'cg_b.7': { when: 'They post a hand on you or the mat', belt: 'blue' },
  'cg_b.7.1': { f: 'common' }, 'cg_b.7.2': { f: 'common' },
  'cg_b.8': { when: 'An arm crosses the centre line', oc: [{ to: 'mt_t', f: 'common' }] },
  'cg_b.8.1': { f: 'common' },
  'cg_b.9': { when: 'They post a hand on you or the mat', energy: 2, oc: [{ to: 'bk_t', f: 'common' }, { to: 'tt_t', f: 'common' }] },
  'cg_b.9.1': { f: 'common' },
  'cg_b.10': { gi: 'gi', when: 'They posture up, hands on your hips', oc: [{ to: 'bk_t', f: 'common' }, { to: 'tt_t', f: 'common' }] },
  'cg_b.11': { when: 'They stand up', oc: [{ to: 'mt_t', f: 'common' }, { to: 'og_t', f: 'rare' }] },
  'cg_b.11.1': { f: 'common' },
  'cg_b.12': { when: 'They stand up', pts: 0 },
  'cg_b.13': { when: 'An arm crosses the centre line' },
  'cg_b.14': { gi: 'gi', when: 'Posture broken, head down', belt: 'blue' },
  'cg_b.15': { when: 'Posture broken, head down' },

  /* ───── Half guard ───── */
  'hg_b.1': { when: 'You have the underhook' },
  'hg_b.1.1': { f: 'common', bait: 'A strong whizzer invites you to drive; experienced tops use it to roll you' }, 'hg_b.1.2': { f: 'common' },
  'hg_b.1.1.1': { oc: [{ to: 'bk_t', f: 'common' }, { to: 'tt_t', f: 'common' }] },
  'hg_b.2': { when: 'They flatten you / cross-face' },
  'hg_b.2.1': { f: 'common' },
  'hg_b.3': { when: 'They stand or sit back', belt: 'blue' },
  'hg_b.3.1': { f: 'common' },
  'hg_b.4': { when: 'They flatten you / cross-face' },
  'hg_b.4.1': { f: 'common' },
  'hg_b.5': { when: 'You have the underhook', oc: [{ to: 'sc_t', f: 'common' }, { to: 'hg_t', f: 'common' }] },
  'hg_b.6': { when: 'They flatten you / cross-face', belt: 'blue' },
  'hg_b.7': { when: 'They whizzer your underhook', oc: [{ to: 'bk_t', f: 'common' }, { to: 'tt_t', f: 'common' }] },
  'hg_b.8': { when: '', pts: 0 },
  'hg_b.9': { when: 'They smash the knee shield', belt: 'blue', kids: false, legal: 'Lockdown twists the knee, not for kids' },

  /* ───── De la Riva / spider / butterfly / X ───── */
  'dlr_b.1': { gi: 'gi' }, 'dlr_b.1.1': { f: 'common' },
  'dlr_b.2': { gi: 'both', belt: 'blue', when: 'They lean forward', oc: [{ to: 'bk_t', f: 'common' }, { to: 'slx_b', f: 'rare' }] },
  'dlr_b.2.1': { f: 'common' }, 'dlr_b.2.2': { f: 'common' },
  'dlr_b.3': { when: 'They stand tall', oc: [{ to: 'sc_t', f: 'common' }, { to: 'og_t', f: 'common' }] },
  'dlr_b.3.1': { f: 'common' },
  'dlr_b.4': { when: 'They squat low', pts: 0 },
  'dlr_b.5': { belt: 'blue', when: 'They clear or turn the hook' },
  'dlr_b.6': { gi: 'gi', when: 'They stand tall' , oc: [{ to: 'sc_t', f: 'common' }, { to: 'tt_t', f: 'common' }] },
  'dlr_b.7': { when: 'They stand tall', oc: [{ to: 'sc_t', f: 'common' }, { to: 'og_t', f: 'common' }] },
  'dlr_b.8': { gi: 'gi', when: 'They clear or turn the hook', pts: 0 },
  'sp_b.1': { gi: 'gi', when: 'They stand with both sleeves gripped' }, 'sp_b.1.1': { f: 'common' }, 'sp_b.1.2': { f: 'common' },
  'sp_b.2': { gi: 'gi', when: 'They pull an arm back' }, 'sp_b.3': { gi: 'gi' }, 'sp_b.4': { gi: 'gi', belt: 'blue', when: 'You have a lasso' }, 'sp_b.5': { gi: 'gi', when: 'They stand and drive forward' }, 'sp_b.6': { gi: 'gi', pts: 0 },
  'bf_b.1': { when: 'They kneel close, chest to chest', oc: [{ to: 'mt_t', f: 'common' }, { to: 'sc_t', f: 'common' }] },
  'bf_b.1.1': { f: 'common' }, 'bf_b.1.2': { f: 'common' },
  'bf_b.2': { when: 'They reach for your head or collar', oc: [{ to: 'bk_t', f: 'common' }, { to: 'tt_t', f: 'common' }] },
  'bf_b.3': { when: 'Their head drops' },
  'bf_b.4': { when: 'They stand up', pts: 0 },
  'bf_b.5': { when: 'They lean in with the head low', oc: [{ to: 'tt_t', f: 'common' }] },
  'bf_b.6': { when: 'You have an overhook', belt: 'blue' },
  'bf_b.7': { when: 'You have an overhook and they lean', belt: 'blue' },
  'xg_b.1': { belt: 'blue', when: 'They stand over you' }, 'xg_b.1.1': { f: 'common' }, 'xg_b.2': { belt: 'blue' }, 'xg_b.3': { belt: 'blue', pts: 0 },
  'slx_b.1': { belt: 'blue', when: 'They stand, one leg trapped' }, 'slx_b.1.1': { f: 'common' },
  'slx_b.2': { belt: 'white', kids: false, legal: 'IBJJF: straight ankle lock allowed from adult white; not for kids/juveniles under 16', energy: 2 },
  'slx_b.3': { belt: 'blue' }, 'slx_b.4': { belt: 'blue', pts: 0 },

  /* ───── Passing ───── */
  'cg_t.1': { when: 'You have posture and a collar grip', energy: 2, pts: 0 }, 'cg_t.1.1': { f: 'common' },
  'cg_t.2': { when: 'They are flat and you have posture', pts: 0 }, 'cg_t.3': { energy: 1, pts: 0 }, 'cg_t.4': { pts: 0 },
  'og_t.1': { gi: 'both', energy: 3, when: 'Feet free, on their back', oc: [{ to: 'sc_t', f: 'common' }, { to: 'kob_t', f: 'common' }, { to: 'tt_t', f: 'rare' }] },
  'og_t.1.1': { f: 'common' },
  'og_t.2': { when: 'Inside their knees / half guard', oc: [{ to: 'sc_t', f: 'common' }, { to: 'hg_t', f: 'common' }, { to: 'bk_t', f: 'rare' }] },
  'og_t.2.1': { f: 'common' }, 'og_t.2.2': { f: 'common' },
  'og_t.3': { when: 'A leg across your hip', oc: [{ to: 'sc_t', f: 'common' }, { to: 'bk_t', f: 'common' }] },
  'og_t.4': { when: 'Feet free, on their back', energy: 3, legal: 'Never slam from the stack' },
  'og_t.5': { when: 'Seated / butterfly guard', energy: 2 }, 'og_t.5.1': { f: 'common' },
  'og_t.6': { belt: 'blue', when: 'Inside their knees / half guard', oc: [{ to: 'sc_t', f: 'common' }, { to: 'kob_t', f: 'common' }] },
  'og_t.7': { when: 'Knee shield', energy: 1 },
  'og_t.8': { belt: 'blue', when: 'Seated / butterfly guard', energy: 1 },
  'og_t.9': { belt: 'blue', when: 'Knee shield' },
  'og_t.10': { pts: 0, energy: 1 },
  'hg_t.1': { oc: [{ to: 'sc_t', f: 'common' }, { to: 'mt_t', f: 'rare' }] }, 'hg_t.2': { oc: [{ to: 'sc_t', f: 'common' }, { to: 'kob_t', f: 'common' }] },
  'hg_t.3': { when: 'They reach for the underhook' }, 'hg_t.4': {}, 'hg_t.5': { when: 'Their arm is across the neck', belt: 'blue' },

  /* ───── Top control ───── */
  'sc_t.1': { when: 'They are flat, elbows loose', energy: 1 }, 'sc_t.1.1': { f: 'common' },
  'sc_t.2': { when: 'They push or extend an arm' }, 'sc_t.2.1': { f: 'common' },
  'sc_t.3': { energy: 1 }, 'sc_t.4': { when: 'They bridge or turn away', oc: [{ to: 'bk_t', f: 'common' }, { to: 'tt_t', f: 'common' }] },
  'sc_t.5': { pts: 0, energy: 1 }, 'sc_t.6': { when: 'An arm goes across their neck', belt: 'blue' },
  'sc_t.7': { gi: 'gi', belt: 'blue' }, 'sc_t.8': { gi: 'gi', belt: 'blue', when: 'They are flat, elbows loose' },
  'sc_t.9': { belt: 'blue' }, 'sc_t.10': { pts: 0, energy: 1 }, 'sc_t.11': { energy: 1 },
  'kob_t.1': { when: 'They push your knee' }, 'kob_t.2': { gi: 'gi', belt: 'blue' }, 'kob_t.3': { energy: 1 },
  'kob_t.4': { when: 'They push with the far arm' }, 'kob_t.5': { gi: 'gi' }, 'kob_t.6': { pts: 0, energy: 1 },
  'mt_t.1': { gi: 'gi', when: 'They defend with elbows in', bait: 'Threatening the second hand makes them reach across and lift the elbow: the armbar opens' }, 'mt_t.1.1': { f: 'common' },
  'mt_t.2': { when: 'They push with an arm' }, 'mt_t.2.1': { f: 'common' },
  'mt_t.3': { when: 'An arm goes across their neck', belt: 'blue' }, 'mt_t.3.1': { f: 'common' },
  'mt_t.4': { when: 'They turn or elbow-escape', oc: [{ to: 'bk_t', f: 'common' }] },
  'mt_t.5': { gi: 'gi', when: 'They defend with elbows in', legal: 'Ezekiel from inside closed guard is illegal for kids; from mount it is fine' },
  'mt_t.6': { when: 'They push with an arm', belt: 'blue' }, 'mt_t.7': { when: 'They push with an arm' },
  'mt_t.8': { when: 'An arm crosses their face or neck', belt: 'blue' }, 'mt_t.9': { pts: 0, energy: 1 }, 'mt_t.10': { pts: 0, energy: 1 },
  'bk_t.1': { when: 'Chin is open', energy: 1 }, 'bk_t.1.1': { f: 'common' }, 'bk_t.1.2': { f: 'common', bait: 'They sometimes give the hook on purpose to turn into you: keep the seat belt' },
  'bk_t.2': { gi: 'gi', when: 'They defend the neck with both hands' }, 'bk_t.3': { when: 'They defend the neck with both hands' },
  'bk_t.4': { pts: 0, energy: 1, legal: 'Body triangle: fine in IBJJF; some kids events forbid it' }, 'bk_t.5': { gi: 'gi' }, 'bk_t.6': { when: 'They turn into you' }, 'bk_t.7': { pts: 0 },
  'tt_t.1': { when: 'Their elbows and knees are apart' }, 'tt_t.1.1': { f: 'common' }, 'tt_t.1.2': { f: 'common' },
  'tt_t.2': { gi: 'nogi', belt: 'blue', when: 'Their head and one arm are exposed' },
  'tt_t.3': { belt: 'blue', when: 'One arm reaches between your legs' }, 'tt_t.4': { when: 'They are tight and heavy' }, 'tt_t.5': { when: 'They posture up' },

  /* ───── Escapes ───── */
  'sc_b.1': { when: 'Space at the hip', energy: 2 }, 'sc_b.1.1': { f: 'common' }, 'sc_b.1.2': { f: 'common' },
  'sc_b.2': { when: 'Their arm or weight is high', energy: 2, oc: [{ to: 'tt_b', f: 'common' }, { to: 'sc_t', f: 'rare' }] },
  'sc_b.3': { when: 'Their arm or weight is high', energy: 3, legal: 'A reversal from bottom side control is not a sweep: no points' }, 'sc_b.4': { belt: 'blue', when: 'Space at the hip', energy: 2 }, 'sc_b.5': { energy: 2 },
  'mt_b.1': { when: 'An arm and a leg are on the same side', energy: 3, legal: 'Escaping mount scores nothing; you earn by what comes next' }, 'mt_b.1.1': { f: 'common' },
  'mt_b.2': { when: 'Their knees are wide', energy: 2 }, 'mt_b.2.1': { f: 'common' },
  'mt_b.3': { energy: 2 }, 'mt_b.4': { when: 'They reach for the collar', energy: 3 }, 'mt_b.5': { belt: 'blue', energy: 2 },
  'bk_b.1': { when: 'You know which side the choking arm is', energy: 2 }, 'bk_b.1.1': { f: 'common' },
  'bk_b.2': { energy: 1 }, 'bk_b.3': { when: 'A hook is loose', energy: 2 }, 'bk_b.4': { belt: 'blue', energy: 2 }, 'bk_b.5': { energy: 1 },
  'tt_b.1': { belt: 'blue', when: 'They are behind you with no hooks', energy: 2 }, 'tt_b.2': { energy: 2 }, 'tt_b.2.1': { f: 'common' },
  'tt_b.3': { when: 'A leg is in reach', energy: 3 }, 'tt_b.4': { when: 'They go for the guillotine' }, 'tt_b.5': { energy: 2 },
};
